// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: proto/item.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "item";

/** Item message */
export interface Item {
  id: number;
  maItem: string;
  ten: string;
  loai: string;
  moTa: string;
  soLuong: number;
  hanhTinh: string;
  setKichHoat: string;
  soSaoPhaLe: number;
  soSaoPhaLeCuongHoa: number;
  soCap: number;
  hanSuDung: number;
  sucManhYeuCau: string;
  linkTexture: string;
  viTri: string;
  chiso: string;
  userId: number;
}

/** Request messages */
export interface UserIdRequest {
  user_id: number;
}

export interface ItemIdRequest {
  id: number;
}

export interface AddItemRequest {
  user_id: number;
  item: Item | undefined;
}

export interface AddMultipleItemsRequest {
  user_id: number;
  items: Item[];
}

export interface Empty {
}

/** Response messages */
export interface ItemsResponse {
  items: Item[];
}

export interface ItemResponse {
  item: Item | undefined;
}

export interface MessageResponse {
  message: string;
}

export const ITEM_PACKAGE_NAME = "item";

/** ===== SERVICE DEFINITION ===== */

export interface ItemServiceClient {
  getItemsByUser(request: UserIdRequest, metadata?: Metadata): Observable<ItemsResponse>;

  addItem(request: AddItemRequest, metadata?: Metadata): Observable<ItemResponse>;

  updateItem(request: Item, metadata?: Metadata): Observable<ItemResponse>;

  deleteItem(request: ItemIdRequest, metadata?: Metadata): Observable<MessageResponse>;

  addMultipleItems(request: AddMultipleItemsRequest, metadata?: Metadata): Observable<ItemsResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface ItemServiceController {
  getItemsByUser(request: UserIdRequest, metadata?: Metadata): Observable<ItemsResponse>;

  addItem(request: AddItemRequest, metadata?: Metadata): Observable<ItemResponse>;

  updateItem(request: Item, metadata?: Metadata): Observable<ItemResponse>;

  deleteItem(request: ItemIdRequest, metadata?: Metadata): Observable<MessageResponse>;

  addMultipleItems(request: AddMultipleItemsRequest, metadata?: Metadata): Observable<ItemsResponse>;
}

export function ItemServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getItemsByUser", "addItem", "updateItem", "deleteItem", "addMultipleItems"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ItemService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ItemService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ITEM_SERVICE_NAME = "ItemService";
